# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://solitude-ethereum.xyz
title: SOLITUDE
email: gaetano.mondelli@gmail.com
#author: Gaetano Mondelli
description: Development framework for Ethereum
copyright: 'Made with ❤️ in the Shoreditch Triangle, London ' 

markdown: kramdown
permalink: pretty
